version: '3.4'

services:
  ksp-luna:
    image: ghcr.io/lunamultiplayer/lunamultiplayer/server:master
    volumes:
      - ksp-luna-config:/LMPServer/Config
      - ksp-luna-plugins:/LMPServer/Plugins
      - ksp-luna-universe:/LMPServer/Universe
      - ksp-luna-logs:/LMPServer/logs
    ports:
      - 8800:8800/udp
      - 8900:8900
    stdin_open: true
    tty: true
    environment:
      - TZ=CET
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}


  filebrowser:
    image: hurlenko/filebrowser
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ksp-luna-config:/data/LMPServer/Config
      - ksp-luna-plugins:/data/LMPServer/Plugins
      - ksp-luna-universe:/data/LMPServer/Universe
      - ksp-luna-logs:/data/LMPServer/logs
      - filebrowser-config:/config
    networks:
      - caddy-public
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        caddy: ${FILEBROWSER_DOMAIN}
        caddy.reverse_proxy: "{{upstreams 8080}}"


volumes:
  ksp-luna-configs:
  ksp-luna-plugins:
  ksp-luna-universe:
  ksp-luna-logs:
  filebrowser-config:


networks:
  caddy-public:
    external: true